# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: ordererOrg
    Domain: samplenet.com
    CA:
        Country: AR
        Province: Buenos Aires
        Locality: Buenos Aires
    Specs:
        - Hostname: orderer
    Template:
      Count: 3
      Start: 1
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:

  - Name: org1
    Domain: org1.samplenet.com
    CA:
        Country: AR
        Province: Buenos Aires
        Locality: Buenos Aires
    Template:
      Count: 1
      Start: 1
    Users:
      Count: 1

