# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: ordererOrg
    Domain: {{.Domain}}
    CA:
      Country: US
      Province: California
      Locality: San Francisco
    Specs:
      - Hostname: orderer
    Template:
      Count: {{.Orderer.Consenters}}
      Start: 1
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
{{range $i := Sequence 1 .PeerOrgs}}
  - Name: org{{$i}}
    Domain: org{{$i}}.{{$.Domain}}
    CA:
      Hostname: ca
      Country: US
      Province: California
      Locality: San Francisco
    Template:
      Count: {{$.PeersPerOrg}}
      Start: 1
      SANS:
        - "localhost"
    Users:
      Count: 1
{{end}}
